### ISSUE TITLE
fs2ff.exe No Longer Opens

### ISSUE THREAD

**Issue by Sim-Dude** [astenlund/fs2ff#69]
I cannot get the app to start anymore.  It worked fine until this morning.  I have uninstalled, downloaded again and tried it again.  I get the warning about being harmful to my computer, but it still won't run. I had used it several times in the last month or so after renewing my Foreflight again.  Is there a log file I can look at?

Thanks,
John

**Comment by astenlund** [comment]
Hi,

I'm no longer actively developing this tool, but I'll try to help. Try to look in the Event Viewer in Windows. Expand Windows Logs and click on Application. Look in the list for Error entries related to fs2ff.

/Andreas

**Comment by Sim-Dude** [comment]
I found another option.

Thanks

**Comment by Sim-Dude** [comment]
Sorry just seeing this.  I have a few errors in the Even Viewer.  All of them happen at the same time.  All are application errors.

- Faulting application name: fs2ff.exe, version: 0.1.14.0, time stamp: 0x614a4452
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xc000041d
Fault offset: 0x000000000002cd29
Faulting process id: 0x3024
Faulting application start time: 0x01d92177f3881a55
Faulting application path: C:\Users\jnava\Desktop\fs2ff.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e593e7e2-2ecb-463d-872a-628af606c1a3
Faulting package full name: 
Faulting package-relative application ID: 

- Faulting application name: fs2ff.exe, version: 0.1.14.0, time stamp: 0x614a4452
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff9f7c2010e
Faulting process id: 0x3024
Faulting application start time: 0x01d92177f3881a55
Faulting application path: C:\Users\jnava\Desktop\fs2ff.exe
Faulting module path: unknown
Report Id: 3eeb8a1c-9654-4323-9fcf-153cf6382f6b
Faulting package full name: 
Faulting package-relative application ID: 

- Application: fs2ff.exe
CoreCLR Version: 4.700.21.47003
.NET Core Version: 3.1.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at fs2ff.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Thanks for you help.

John
