### ISSUE TITLE
App crashing right after opening with FS2020 v1.9.5.0

### ISSUE THREAD

**Issue by ianneub** [astenlund/fs2ff#9]
Hello,

Thanks for this app, it was working great for me before the patch today of Flight Simulator 2020 v1.9.5.0.

After opening the app, after about 2 seconds the app exits.

I found these errors in the windows application log

```
Application: fs2ff.exe
CoreCLR Version: 4.700.20.41105
.NET Core Version: 3.1.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(IPEndPoint localEP)
   at fs2ff.IpDetectionService.<>c__DisplayClass4_0.<<StartAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at fs2ff.IpDetectionService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at fs2ff.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at fs2ff.App.Main()
```

```
Faulting application name: fs2ff.exe, version: 0.1.8.0, time stamp: 0x5f3ed523
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1049, time stamp: 0x1b835a75
Exception code: 0xe0434352
Fault offset: 0x0000000000043b29
Faulting process id: 0x1940
Faulting application start time: 0x01d6a1b6e02532f1
Faulting application path: D:\Media\Software\Games\MS Flight Simulator\fs2ff.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fc693af6-6cf7-4a23-905a-61ff0efe5139
Faulting package full name: 
Faulting package-relative application ID: 
```

Edit: Running as Administrator did not fix it.

**Comment by astenlund** [comment]
Thanks, I'll have a look.

**Comment by ianneub** [comment]
Odd update: today the app seems to start ok. It connects to FS2020 just fine. I don't think I installed any updates to the machine or even rebooted this machine since yesterday.  ¯\_(ツ)_/¯

**Comment by astenlund** [comment]
Did you restart the computer before it started working? It seems like a permission problem related to the IP auto-detect function. I'll update the app so that it doesn't crash, should it happen again.

/Andreas

**Comment by ianneub** [comment]
Not that I know of, but I'm not 100% sure. Another data point if it helps: I have the auto detect IP setting turned off as I want to send the data to multiple devices. Thanks again!

**Comment by astenlund** [comment]
Ok, thanks. I should be able to push out an anti-crash update soon-ish.

**Comment by astenlund** [comment]
New version out, check it out here: https://github.com/astenlund/fs2ff/releases/latest

Please let me know if this fixes your issue.

**Comment by ianneub** [comment]
Seems to work really well. Thanks!
